<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="René Canales, Research Helper">
<meta name="dcterms.date" content="2025-06-30">
<title>Measuring perceptions and preferences about meritocracy in school in Chile</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="Replicate-Liu MeritFactorial_files/libs/clipboard/clipboard.min.js"></script>
<script src="Replicate-Liu MeritFactorial_files/libs/quarto-html/quarto.js"></script>
<script src="Replicate-Liu MeritFactorial_files/libs/quarto-html/popper.min.js"></script>
<script src="Replicate-Liu MeritFactorial_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Replicate-Liu MeritFactorial_files/libs/quarto-html/anchor.min.js"></script>
<link href="Replicate-Liu MeritFactorial_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Replicate-Liu MeritFactorial_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Replicate-Liu MeritFactorial_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Replicate-Liu MeritFactorial_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Replicate-Liu MeritFactorial_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script src="Replicate-Liu%20MeritFactorial_files/libs/kePrint-0.0.1/kePrint.js"></script><link href="Replicate-Liu%20MeritFactorial_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="Replicate-Liu%20MeritFactorial_files/libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="Replicate-Liu%20MeritFactorial_files/libs/bsTable-3.3.7/bootstrapTable.js"></script>
</head>
<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full"><div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Measuring perceptions and preferences about meritocracy in school in Chile</h1>
            <p class="subtitle lead">Longitudinal Invariance EduMer using Liu et al.&nbsp;(2017) Replication</p>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>René Canales, Research Helper </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 30, 2025</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2"><h2 id="toc-title">Contenidos</h2>
   
  <ul class="collapse">
<li><a href="#libraries" id="toc-libraries" class="nav-link active" data-scroll-target="#libraries"><span class="header-section-number">1</span> Libraries</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2</span> Data</a></li>
  <li>
<a href="#invariance-models" id="toc-invariance-models" class="nav-link" data-scroll-target="#invariance-models"><span class="header-section-number">3</span> Invariance Models</a>
  <ul class="collapse">
<li><a href="#configural" id="toc-configural" class="nav-link" data-scroll-target="#configural"><span class="header-section-number">3.1</span> Configural</a></li>
  <li><a href="#weak-model" id="toc-weak-model" class="nav-link" data-scroll-target="#weak-model"><span class="header-section-number">3.2</span> Weak Model</a></li>
  <li><a href="#strong" id="toc-strong" class="nav-link" data-scroll-target="#strong"><span class="header-section-number">3.3</span> Strong</a></li>
  <li><a href="#strict-model" id="toc-strict-model" class="nav-link" data-scroll-target="#strict-model"><span class="header-section-number">3.4</span> Strict Model</a></li>
  <li><a href="#compare-fit" id="toc-compare-fit" class="nav-link" data-scroll-target="#compare-fit"><span class="header-section-number">3.5</span> Compare Fit</a></li>
  </ul>
</li>
  <li><a href="#possible-error-sources" id="toc-possible-error-sources" class="nav-link" data-scroll-target="#possible-error-sources"><span class="header-section-number">4</span> Possible Error Sources</a></li>
  </ul></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content"><section id="libraries" class="level1" data-number="1"><h1 data-number="1">
<span class="header-section-number">1</span> Libraries</h1>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw">if</span> <span class="op">(</span><span class="op">!</span><span class="kw"><a href="https://rdrr.io/r/base/library.html">require</a></span><span class="op">(</span><span class="st"><a href="https://github.com/trinker/pacman">"pacman"</a></span><span class="op">)</span><span class="op">)</span> <span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"pacman"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu">pacman</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/pacman/man/p_load.html">p_load</a></span><span class="op">(</span></span>
<span>  <span class="va">tidyverse</span>,</span>
<span>  <span class="va">sjmisc</span>,</span>
<span>  <span class="va">sjPlot</span>,</span>
<span>  <span class="va">here</span>,</span>
<span>  <span class="va">lavaan</span>,</span>
<span>  <span class="va">psych</span>,</span>
<span>  <span class="va">corrplot</span>,</span>
<span>  <span class="va">ggdist</span>,</span>
<span>  <span class="va">patchwork</span>, <span class="co">#Combina múltiples gráficos de ggplot2 en una sola figura</span></span>
<span>  <span class="va">semTools</span>,</span>
<span>  <span class="va">gtools</span>,</span>
<span>  <span class="va">kableExtra</span></span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>scipen <span class="op">=</span> <span class="fl">999</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="data" class="level1" data-number="2"><h1 data-number="2">
<span class="header-section-number">2</span> Data</h1>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/load.html">load</a></span><span class="op">(</span>file <span class="op">=</span> <span class="fu">here</span><span class="op">(</span><span class="st">"output"</span>, <span class="st">"data"</span>, <span class="st">"db_long_proc.RData"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">db_long</span><span class="op">)</span></span>
<span><span class="fu">glimpse</span><span class="op">(</span><span class="va">db_long</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">db_long</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">db_invariance</span> <span class="op">&lt;-</span></span>
<span>  <span class="va">db_long</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">select</span><span class="op">(</span><span class="va">id_estudiante</span>, <span class="va">ola</span>, <span class="fu">starts_with</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perc"</span>, <span class="st">"pref"</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">pivot_wider</span><span class="op">(</span></span>
<span>    id_cols <span class="op">=</span> <span class="va">id_estudiante</span>,</span>
<span>    names_from <span class="op">=</span> <span class="va">ola</span>,</span>
<span>    names_glue <span class="op">=</span> <span class="st">"{.value}{ola}"</span>,</span>
<span>    values_from <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span></span>
<span>      <span class="va">perc_effort</span>, <span class="va">perc_talent</span>,</span>
<span>      <span class="va">perc_rich_parents</span>, <span class="va">perc_contact</span>,</span>
<span>      <span class="va">pref_effort</span>, <span class="va">pref_talent</span>,</span>
<span>      <span class="va">pref_rich_parents</span>, <span class="va">pref_contact</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/stats/na.fail.html">na.omit</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span></span>
<span>  <span class="fu">rename_with</span><span class="op">(</span><span class="op">~</span> <span class="fu">str_replace_all</span><span class="op">(</span><span class="va">.</span>, <span class="st">"_"</span>, <span class="st">""</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">db_invariance</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">db_long</span><span class="op">)</span></span>
<span></span>
<span><span class="va">db_invariance</span> <span class="op">&lt;-</span> <span class="va">db_invariance</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    <span class="fu">across</span><span class="op">(</span></span>
<span>      .cols <span class="op">=</span> <span class="op">-</span><span class="va">idestudiante</span>,</span>
<span>      .fns <span class="op">=</span> <span class="op">~</span> <span class="fu">case_when</span><span class="op">(</span><span class="va">.</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">~</span> <span class="fl">0</span>,</span>
<span>                         <span class="va">.</span> <span class="op">==</span> <span class="fl">2</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                         <span class="va">.</span> <span class="op">==</span> <span class="fl">3</span> <span class="op">~</span> <span class="fl">2</span>,</span>
<span>                         <span class="va">.</span> <span class="op">==</span> <span class="fl">4</span> <span class="op">~</span> <span class="fl">3</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span>
<span></span>
<span><span class="va">db_invariance</span> <span class="op">&lt;-</span> <span class="va">db_invariance</span> <span class="op">%&gt;%</span> </span>
<span>  <span class="fu">mutate</span><span class="op">(</span></span>
<span>    <span class="fu">across</span><span class="op">(</span></span>
<span>      .cols <span class="op">=</span> <span class="op">-</span><span class="va">idestudiante</span>,</span>
<span>      .fns <span class="op">=</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">ordered</a></span><span class="op">(</span><span class="va">.</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span>  <span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="invariance-models" class="level1" data-number="3"><h1 data-number="3">
<span class="header-section-number">3</span> Invariance Models</h1>
<section id="configural" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="configural">
<span class="header-section-number">3.1</span> Configural</h2>
<div class="cell" data-tbl-cap="Configural Model">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">baseline_model_smt</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="st">'</span></span>
<span><span class="st"></span></span>
<span><span class="st">###########################################</span></span>
<span><span class="st"># Definición de factores (1 marcador por factor)</span></span>
<span><span class="st">###########################################</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  =~ 1*perceffort1     + perctalent1</span></span>
<span><span class="st">percmerit2  =~ 1*perceffort2     + perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percnmerit1 =~ 1*percrichparents1 + perccontact1</span></span>
<span><span class="st">percnmerit2 =~ 1*percrichparents2 + perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefmerit1  =~ 1*prefeffort1     + preftalent1</span></span>
<span><span class="st">prefmerit2  =~ 1*prefeffort2     + preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefnmerit1 =~ 1*prefrichparents1 + prefcontact1</span></span>
<span><span class="st">prefnmerit2 =~ 1*prefrichparents2 + prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st">###########################################</span></span>
<span><span class="st"># Covarianzas entre errores (mismo ítem, distintas olas)</span></span>
<span><span class="st">###########################################</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ perceffort2</span></span>
<span><span class="st">perctalent1 ~~ perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percrichparents1 ~~ percrichparents2</span></span>
<span><span class="st">perccontact1     ~~ perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefeffort1 ~~ prefeffort2</span></span>
<span><span class="st">preftalent1 ~~ preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefrichparents1 ~~ prefrichparents2</span></span>
<span><span class="st">prefcontact1     ~~ prefcontact2</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span></span>
<span></span>
<span></span>
<span><span class="co"># Estimación del modelo</span></span>
<span><span class="va">fit_baseline</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span><span class="va">baseline_model_smt</span>, data <span class="op">=</span> <span class="va">db_invariance</span>,</span>
<span>                    ordered <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perceffort1"</span>, <span class="st">"perctalent1"</span>, <span class="st">"perceffort2"</span>, <span class="st">"perctalent2"</span>,</span>
<span>                                <span class="st">"percrichparents1"</span>, <span class="st">"perccontact1"</span>, <span class="st">"percrichparents2"</span>, <span class="st">"perccontact2"</span>,</span>
<span>                                <span class="st">"prefeffort1"</span>, <span class="st">"preftalent1"</span>, <span class="st">"prefeffort2"</span>, <span class="st">"preftalent2"</span>,</span>
<span>                                <span class="st">"prefrichparents1"</span>, <span class="st">"prefcontact1"</span>, <span class="st">"prefrichparents2"</span>, <span class="st">"prefcontact2"</span><span class="op">)</span>,</span>
<span>                    parameterization <span class="op">=</span> <span class="st">"theta"</span>,</span>
<span>                    estimator <span class="op">=</span> <span class="st">"WLSMV"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Resultados</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_baseline</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="weak-model" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="weak-model">
<span class="header-section-number">3.2</span> Weak Model</h2>
<div class="cell" data-tbl-cap="Weak Model">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">loadinginv_model_smt</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="st">'</span></span>
<span><span class="st"></span></span>
<span><span class="st"># Igualación de cargas (invarianza débil)</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  =~ 1*perceffort1 + pe_loading*perctalent1</span></span>
<span><span class="st">percmerit2  =~ 1*perceffort2 + pe_loading*perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percnmerit1 =~ 1*percrichparents1 + prc_loading*perccontact1</span></span>
<span><span class="st">percnmerit2 =~ 1*percrichparents2 + prc_loading*perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefmerit1  =~ 1*prefeffort1 + pfe_loading*preftalent1</span></span>
<span><span class="st">prefmerit2  =~ 1*prefeffort2 + pfe_loading*preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefnmerit1 =~ 1*prefrichparents1 + pfrc_loading*prefcontact1</span></span>
<span><span class="st">prefnmerit2 =~ 1*prefrichparents2 + pfrc_loading*prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Varianzas y covarianzas latentes</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  ~~ percmerit1 + percmerit2</span></span>
<span><span class="st">percmerit2  ~~ percmerit2</span></span>
<span><span class="st">percnmerit1 ~~ percnmerit1 + percnmerit2</span></span>
<span><span class="st">percnmerit2 ~~ percnmerit2</span></span>
<span><span class="st">prefmerit1  ~~ prefmerit1 + prefmerit2</span></span>
<span><span class="st">prefmerit2  ~~ prefmerit2</span></span>
<span><span class="st">prefnmerit1 ~~ prefnmerit1 + prefnmerit2</span></span>
<span><span class="st">prefnmerit2 ~~ prefnmerit2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Umbrales (uno igualado por ítem)</span></span>
<span><span class="st"></span></span>
<span><span class="st"># perceffort1 | pe1t1*t1 + pe1t2*t2</span></span>
<span><span class="st"># perceffort2 | pe2t1*t1 + pe2t2*t2</span></span>
<span><span class="st"># perctalent1 | pt1t1*t1 + pt1t2*t2</span></span>
<span><span class="st"># perctalent2 | pt2t1*t1 + pt2t2*t2</span></span>
<span><span class="st"># percrichparents1 | prp1t1*t1 + prp1t2*t2</span></span>
<span><span class="st"># percrichparents2 | prp2t1*t1 + prp2t2*t2</span></span>
<span><span class="st"># perccontact1 | pc1t1*t1 + pc1t2*t2</span></span>
<span><span class="st"># perccontact2 | pc2t1*t1 + pc2t2*t2</span></span>
<span><span class="st"># prefeffort1 | pre1t1*t1 + pre1t2*t2</span></span>
<span><span class="st"># prefeffort2 | pre2t1*t1 + pre2t2*t2</span></span>
<span><span class="st"># preftalent1 | prt1t1*t1 + prt1t2*t2</span></span>
<span><span class="st"># preftalent2 | prt2t1*t1 + prt2t2*t2</span></span>
<span><span class="st"># prefrichparents1 | pfrp1t1*t1 + pfrp1t2*t2</span></span>
<span><span class="st"># prefrichparents2 | pfrp2t1*t1 + pfrp2t2*t2</span></span>
<span><span class="st"># prefcontact1 | pfc1t1*t1 + pfc1t2*t2</span></span>
<span><span class="st"># prefcontact2 | pfc2t1*t1 + pfc2t2*t2</span></span>
<span><span class="st"> </span></span>
<span><span class="st"></span></span>
<span><span class="st"># Covarianzas entre errores</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ perceffort2</span></span>
<span><span class="st">perctalent1 ~~ perctalent2</span></span>
<span><span class="st">percrichparents1 ~~ percrichparents2</span></span>
<span><span class="st">perccontact1 ~~ perccontact2</span></span>
<span><span class="st">prefeffort1 ~~ prefeffort2</span></span>
<span><span class="st">preftalent1 ~~ preftalent2</span></span>
<span><span class="st">prefrichparents1 ~~ prefrichparents2</span></span>
<span><span class="st">prefcontact1 ~~ prefcontact2</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span></span>
<span></span>
<span><span class="va">fit_loadinginv</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span><span class="va">loadinginv_model_smt</span>, data <span class="op">=</span> <span class="va">db_invariance</span>,</span>
<span>                      ordered <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perceffort1"</span>, <span class="st">"perctalent1"</span>, <span class="st">"perceffort2"</span>, <span class="st">"perctalent2"</span>,</span>
<span>                                  <span class="st">"percrichparents1"</span>, <span class="st">"perccontact1"</span>, <span class="st">"percrichparents2"</span>, <span class="st">"perccontact2"</span>,</span>
<span>                                  <span class="st">"prefeffort1"</span>, <span class="st">"preftalent1"</span>, <span class="st">"prefeffort2"</span>, <span class="st">"preftalent2"</span>,</span>
<span>                                  <span class="st">"prefrichparents1"</span>, <span class="st">"prefcontact1"</span>, <span class="st">"prefrichparents2"</span>, <span class="st">"prefcontact2"</span><span class="op">)</span>,</span>
<span>                      parameterization <span class="op">=</span> <span class="st">"theta"</span>,</span>
<span>                      estimator <span class="op">=</span> <span class="st">"WLSMV"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_loadinginv</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="strong" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="strong">
<span class="header-section-number">3.3</span> Strong</h2>
<div class="cell" data-tbl-cap="Strong Model">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">thresholdinv_model_smt</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="st">'</span></span>
<span><span class="st"></span></span>
<span><span class="st"># Igualación de cargas (como en el modelo débil)</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  =~ 1*perceffort1 + pe_loading*perctalent1</span></span>
<span><span class="st">percmerit2  =~ 1*perceffort2 + pe_loading*perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percnmerit1 =~ 1*percrichparents1 + prc_loading*perccontact1</span></span>
<span><span class="st">percnmerit2 =~ 1*percrichparents2 + prc_loading*perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefmerit1  =~ 1*prefeffort1 + pfe_loading*preftalent1</span></span>
<span><span class="st">prefmerit2  =~ 1*prefeffort2 + pfe_loading*preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefnmerit1 =~ 1*prefrichparents1 + pfrc_loading*prefcontact1</span></span>
<span><span class="st">prefnmerit2 =~ 1*prefrichparents2 + pfrc_loading*prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Varianzas y covarianzas latentes</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  ~~ percmerit1 + percmerit2</span></span>
<span><span class="st">percmerit2  ~~ percmerit2</span></span>
<span><span class="st">percnmerit1 ~~ percnmerit1 + percnmerit2</span></span>
<span><span class="st">percnmerit2 ~~ percnmerit2</span></span>
<span><span class="st">prefmerit1  ~~ prefmerit1 + prefmerit2</span></span>
<span><span class="st">prefmerit2  ~~ prefmerit2</span></span>
<span><span class="st">prefnmerit1 ~~ prefnmerit1 + prefnmerit2</span></span>
<span><span class="st">prefnmerit2 ~~ prefnmerit2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Thresholds iguales entre olas (invarianza fuerte)</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1     | pe_t1*t1 + pe_t2*t2</span></span>
<span><span class="st">perceffort2     | pe_t1*t1 + pe_t2*t2</span></span>
<span><span class="st">perctalent1     | pt_t1*t1 + pt_t2*t2</span></span>
<span><span class="st">perctalent2     | pt_t1*t1 + pt_t2*t2</span></span>
<span><span class="st">percrichparents1| prp_t1*t1 + prp_t2*t2</span></span>
<span><span class="st">percrichparents2| prp_t1*t1 + prp_t2*t2</span></span>
<span><span class="st">perccontact1    | pc_t1*t1 + pc_t2*t2</span></span>
<span><span class="st">perccontact2    | pc_t1*t1 + pc_t2*t2</span></span>
<span><span class="st">prefeffort1     | pre_t1*t1 + pre_t2*t2</span></span>
<span><span class="st">prefeffort2     | pre_t1*t1 + pre_t2*t2</span></span>
<span><span class="st">preftalent1     | prt_t1*t1 + prt_t2*t2</span></span>
<span><span class="st">preftalent2     | prt_t1*t1 + prt_t2*t2</span></span>
<span><span class="st">prefrichparents1| pfrp_t1*t1 + pfrp_t2*t2</span></span>
<span><span class="st">prefrichparents2| pfrp_t1*t1 + pfrp_t2*t2</span></span>
<span><span class="st">prefcontact1    | pfc_t1*t1 + pfc_t2*t2</span></span>
<span><span class="st">prefcontact2    | pfc_t1*t1 + pfc_t2*t2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Interceptos fijos</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 + perctalent1 ~ 0*1</span></span>
<span><span class="st">perceffort2 + perctalent2 ~ 0*1</span></span>
<span><span class="st">percrichparents1 + perccontact1 ~ 0*1</span></span>
<span><span class="st">percrichparents2 + perccontact2 ~ 0*1</span></span>
<span><span class="st">prefeffort1 + preftalent1 ~ 0*1</span></span>
<span><span class="st">prefeffort2 + preftalent2 ~ 0*1</span></span>
<span><span class="st">prefrichparents1 + prefcontact1 ~ 0*1</span></span>
<span><span class="st">prefrichparents2 + prefcontact2 ~ 0*1</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Varianzas únicas</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ 1*perceffort1</span></span>
<span><span class="st">perctalent1 ~~ 1*perctalent1</span></span>
<span><span class="st">percrichparents1 ~~ 1*percrichparents1</span></span>
<span><span class="st">perccontact1 ~~ 1*perccontact1</span></span>
<span><span class="st">prefeffort1 ~~ 1*prefeffort1</span></span>
<span><span class="st">preftalent1 ~~ 1*preftalent1</span></span>
<span><span class="st">prefrichparents1 ~~ 1*prefrichparents1</span></span>
<span><span class="st">prefcontact1 ~~ 1*prefcontact1</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort2 ~~ NA*perceffort2</span></span>
<span><span class="st">perctalent2 ~~ NA*perctalent2</span></span>
<span><span class="st">percrichparents2 ~~ NA*percrichparents2</span></span>
<span><span class="st">perccontact2 ~~ NA*perccontact2</span></span>
<span><span class="st">prefeffort2 ~~ NA*prefeffort2</span></span>
<span><span class="st">preftalent2 ~~ NA*preftalent2</span></span>
<span><span class="st">prefrichparents2 ~~ NA*prefrichparents2</span></span>
<span><span class="st">prefcontact2 ~~ NA*prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Covarianzas entre errores longitudinales</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ perceffort2</span></span>
<span><span class="st">perctalent1 ~~ perctalent2</span></span>
<span><span class="st">percrichparents1 ~~ percrichparents2</span></span>
<span><span class="st">perccontact1 ~~ perccontact2</span></span>
<span><span class="st">prefeffort1 ~~ prefeffort2</span></span>
<span><span class="st">preftalent1 ~~ preftalent2</span></span>
<span><span class="st">prefrichparents1 ~~ prefrichparents2</span></span>
<span><span class="st">prefcontact1 ~~ prefcontact2</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_thresholdinv</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span><span class="va">thresholdinv_model_smt</span>, data <span class="op">=</span> <span class="va">db_invariance</span>,</span>
<span>                        ordered <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perceffort1"</span>, <span class="st">"perctalent1"</span>, <span class="st">"perceffort2"</span>, <span class="st">"perctalent2"</span>,</span>
<span>                                    <span class="st">"percrichparents1"</span>, <span class="st">"perccontact1"</span>, <span class="st">"percrichparents2"</span>, <span class="st">"perccontact2"</span>,</span>
<span>                                    <span class="st">"prefeffort1"</span>, <span class="st">"preftalent1"</span>, <span class="st">"prefeffort2"</span>, <span class="st">"preftalent2"</span>,</span>
<span>                                    <span class="st">"prefrichparents1"</span>, <span class="st">"prefcontact1"</span>, <span class="st">"prefrichparents2"</span>, <span class="st">"prefcontact2"</span><span class="op">)</span>,</span>
<span>                        parameterization <span class="op">=</span> <span class="st">"theta"</span>,</span>
<span>                        estimator <span class="op">=</span> <span class="st">"WLSMV"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">fit_thresholdinv</span>, fit.measures <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="strict-model" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="strict-model">
<span class="header-section-number">3.4</span> Strict Model</h2>
<div class="cell" data-tbl-cap="Scalar Model">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">uniquenessinv_model_smt</span> <span class="op">&lt;-</span> <span class="op">(</span><span class="st">'</span></span>
<span><span class="st"></span></span>
<span><span class="st"># Cargas factoriales (invarianza débil)</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  =~ 1*perceffort1 + pe_loading*perctalent1</span></span>
<span><span class="st">percmerit2  =~ 1*perceffort2 + pe_loading*perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percnmerit1 =~ 1*percrichparents1 + prc_loading*perccontact1</span></span>
<span><span class="st">percnmerit2 =~ 1*percrichparents2 + prc_loading*perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefmerit1  =~ 1*prefeffort1 + pfe_loading*preftalent1</span></span>
<span><span class="st">prefmerit2  =~ 1*prefeffort2 + pfe_loading*preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefnmerit1 =~ 1*prefrichparents1 + pfrc_loading*prefcontact1</span></span>
<span><span class="st">prefnmerit2 =~ 1*prefrichparents2 + pfrc_loading*prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Varianzas y covarianzas de factores latentes</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  ~~ percmerit1 + percmerit2</span></span>
<span><span class="st">percmerit2  ~~ percmerit2</span></span>
<span><span class="st">percnmerit1 ~~ percnmerit1 + percnmerit2</span></span>
<span><span class="st">percnmerit2 ~~ percnmerit2</span></span>
<span><span class="st">prefmerit1  ~~ prefmerit1 + prefmerit2</span></span>
<span><span class="st">prefmerit2  ~~ prefmerit2</span></span>
<span><span class="st">prefnmerit1 ~~ prefnmerit1 + prefnmerit2</span></span>
<span><span class="st">prefnmerit2 ~~ prefnmerit2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Medias latentes</span></span>
<span><span class="st"></span></span>
<span><span class="st">percmerit1  ~ 0*1</span></span>
<span><span class="st">percmerit2  ~ 1</span></span>
<span><span class="st">percnmerit1 ~ 0*1</span></span>
<span><span class="st">percnmerit2 ~ 1</span></span>
<span><span class="st">prefmerit1  ~ 0*1</span></span>
<span><span class="st">prefmerit2  ~ 1</span></span>
<span><span class="st">prefnmerit1 ~ 0*1</span></span>
<span><span class="st">prefnmerit2 ~ 1</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Umbrales (invarianza fuerte)</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1     | pe_t1*t1 + pe_t2*t2</span></span>
<span><span class="st">perceffort2     | pe_t1*t1 + pe_t2*t2</span></span>
<span><span class="st">perctalent1     | pt_t1*t1 + pt_t2*t2</span></span>
<span><span class="st">perctalent2     | pt_t1*t1 + pt_t2*t2</span></span>
<span><span class="st">percrichparents1| prp_t1*t1 + prp_t2*t2</span></span>
<span><span class="st">percrichparents2| prp_t1*t1 + prp_t2*t2</span></span>
<span><span class="st">perccontact1    | pc_t1*t1 + pc_t2*t2</span></span>
<span><span class="st">perccontact2    | pc_t1*t1 + pc_t2*t2</span></span>
<span><span class="st">prefeffort1     | pre_t1*t1 + pre_t2*t2</span></span>
<span><span class="st">prefeffort2     | pre_t1*t1 + pre_t2*t2</span></span>
<span><span class="st">preftalent1     | prt_t1*t1 + prt_t2*t2</span></span>
<span><span class="st">preftalent2     | prt_t1*t1 + prt_t2*t2</span></span>
<span><span class="st">prefrichparents1| pfrp_t1*t1 + pfrp_t2*t2</span></span>
<span><span class="st">prefrichparents2| pfrp_t1*t1 + pfrp_t2*t2</span></span>
<span><span class="st">prefcontact1    | pfc_t1*t1 + pfc_t2*t2</span></span>
<span><span class="st">prefcontact2    | pfc_t1*t1 + pfc_t2*t2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Interceptos fijos</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 + perctalent1 ~ 0*1</span></span>
<span><span class="st">perceffort2 + perctalent2 ~ 0*1</span></span>
<span><span class="st">percrichparents1 + perccontact1 ~ 0*1</span></span>
<span><span class="st">percrichparents2 + perccontact2 ~ 0*1</span></span>
<span><span class="st">prefeffort1 + preftalent1 ~ 0*1</span></span>
<span><span class="st">prefeffort2 + preftalent2 ~ 0*1</span></span>
<span><span class="st">prefrichparents1 + prefcontact1 ~ 0*1</span></span>
<span><span class="st">prefrichparents2 + prefcontact2 ~ 0*1</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Varianzas únicas (invarianza estricta)</span></span>
<span><span class="st"># Fijadas a 1 en todas las olas</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ 1*perceffort1</span></span>
<span><span class="st">perceffort2 ~~ 1*perceffort2</span></span>
<span><span class="st">perctalent1 ~~ 1*perctalent1</span></span>
<span><span class="st">perctalent2 ~~ 1*perctalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">percrichparents1 ~~ 1*percrichparents1</span></span>
<span><span class="st">percrichparents2 ~~ 1*percrichparents2</span></span>
<span><span class="st">perccontact1 ~~ 1*perccontact1</span></span>
<span><span class="st">perccontact2 ~~ 1*perccontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefeffort1 ~~ 1*prefeffort1</span></span>
<span><span class="st">prefeffort2 ~~ 1*prefeffort2</span></span>
<span><span class="st">preftalent1 ~~ 1*preftalent1</span></span>
<span><span class="st">preftalent2 ~~ 1*preftalent2</span></span>
<span><span class="st"></span></span>
<span><span class="st">prefrichparents1 ~~ 1*prefrichparents1</span></span>
<span><span class="st">prefrichparents2 ~~ 1*prefrichparents2</span></span>
<span><span class="st">prefcontact1 ~~ 1*prefcontact1</span></span>
<span><span class="st">prefcontact2 ~~ 1*prefcontact2</span></span>
<span><span class="st"></span></span>
<span><span class="st"></span></span>
<span><span class="st"># Covarianzas entre errores (mismo ítem, diferente ola)</span></span>
<span><span class="st"></span></span>
<span><span class="st">perceffort1 ~~ perceffort2</span></span>
<span><span class="st">perctalent1 ~~ perctalent2</span></span>
<span><span class="st">percrichparents1 ~~ percrichparents2</span></span>
<span><span class="st">perccontact1 ~~ perccontact2</span></span>
<span><span class="st">prefeffort1 ~~ prefeffort2</span></span>
<span><span class="st">preftalent1 ~~ preftalent2</span></span>
<span><span class="st">prefrichparents1 ~~ prefrichparents2</span></span>
<span><span class="st">prefcontact1 ~~ prefcontact2</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">fit_uniquenessinv</span> <span class="op">&lt;-</span> <span class="fu">cfa</span><span class="op">(</span><span class="va">uniquenessinv_model_smt</span>, data <span class="op">=</span> <span class="va">db_invariance</span>,</span>
<span>                         ordered <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"perceffort1"</span>, <span class="st">"perctalent1"</span>, <span class="st">"perceffort2"</span>, <span class="st">"perctalent2"</span>,</span>
<span>                                     <span class="st">"percrichparents1"</span>, <span class="st">"perccontact1"</span>, <span class="st">"percrichparents2"</span>, <span class="st">"perccontact2"</span>,</span>
<span>                                     <span class="st">"prefeffort1"</span>, <span class="st">"preftalent1"</span>, <span class="st">"prefeffort2"</span>, <span class="st">"preftalent2"</span>,</span>
<span>                                     <span class="st">"prefrichparents1"</span>, <span class="st">"prefcontact1"</span>, <span class="st">"prefrichparents2"</span>, <span class="st">"prefcontact2"</span><span class="op">)</span>,</span>
<span>                         parameterization <span class="op">=</span> <span class="st">"theta"</span>,</span>
<span>                         estimator <span class="op">=</span> <span class="st">"WLSMV"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="compare-fit" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="compare-fit">
<span class="header-section-number">3.5</span> Compare Fit</h2>
<div class="cell">
<table class="table table-striped table-bordered table-condensed caption-top table-sm small" data-quarto-postprocess="true">
<caption>Scalar Model</caption>
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">χ^2 (df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RMSEA (90 CI)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ χ^2 (Δ df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ RMSEA</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Decision</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Configural</td>
<td style="text-align: center; width: 4cm;">117.7 (68)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.035 (0.024-0.046)</td>
<td style="text-align: center; width: 4cm;">0 (0)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 3.5cm;">Reference</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Weak</td>
<td style="text-align: center; width: 4cm;">122.51 (72)</td>
<td style="text-align: center; width: 4cm;">0.990</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.034 (0.024-0.045)</td>
<td style="text-align: center; width: 4cm;">4.809 (4)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.001</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Strong</td>
<td style="text-align: center; width: 4cm;">128.53 (80)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.032 (0.021-0.042)</td>
<td style="text-align: center; width: 4cm;">6.02 (8)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.002</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Strict</td>
<td style="text-align: center; width: 4cm;">130.17 (84)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.031 (0.02-0.04)</td>
<td style="text-align: center; width: 4cm;">1.635 (4)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.002</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
</tbody>
</table>
</div>
<p>A series of nested confirmatory factor analysis (CFA) models was estimated to assess the longitudinal measurement invariance of the constructs across different waves of the study. The evaluation began with the configural model, which allows all parameters (loadings, intercepts, and residuals) to vary freely across time. This model served as the baseline for subsequent comparisons and demonstrated good fit to the data, with χ²(68) = 117.7, a Comparative Fit Index (CFI) of 0.991, and a Root Mean Square Error of Approximation (RMSEA) of 0.035, with a 90% confidence interval ranging from 0.024 to 0.046. These indices suggest that the same factorial structure is replicated across time points, meaning that the general configuration of items and latent variables remains stable.</p>
<p>Subsequently, the weak invariance model was tested by constraining the factor loadings to be equal across waves. This model also showed excellent fit: χ²(72) = 122.51, CFI = 0.990, RMSEA = 0.034 (90% CI: 0.024–0.045). The comparison with the configural model revealed a negligible and non-significant change in model fit, with Δχ²(4) = 4.809, ΔCFI = 0.000, and ΔRMSEA = -0.001. These results support the assumption of weak invariance, indicating that the strength of the relationship between items and latent constructs is consistent over time.</p>
<p>The strong invariance model introduced additional constraints by setting item intercepts equal across time points, in addition to the equality of factor loadings. This model yielded a χ²(80) = 128.53, CFI = 0.991, and RMSEA = 0.032 (90% CI: 0.021–0.042). The changes in fit statistics relative to the weak model were Δχ²(8) = 6.02, ΔCFI = 0.000, and ΔRMSEA = -0.002. These minimal differences suggest that the additional constraints did not significantly impair the model’s fit. Therefore, strong invariance is supported, meaning that individuals with the same latent trait level are expected to have the same observed item scores across waves.</p>
<p>Finally, the strict invariance model imposed equality constraints on residual variances in addition to the loadings and intercepts. This model also showed good fit: χ²(84) = 130.17, CFI = 0.991, RMSEA = 0.031 (90% CI: 0.020–0.040). The comparison with the strong model revealed a Δχ²(4) = 1.635, ΔCFI = 0.000, and ΔRMSEA = -0.002. These changes are minimal and fall well within recommended thresholds for model comparison, indicating that strict invariance is also supported.</p>
<p>In summary, the results support full longitudinal measurement invariance—configural, weak, strong, and strict—suggesting that the constructs are measured equivalently across time. This justifies meaningful comparisons of latent means, variances, and covariances over time, and provides strong evidence of the temporal stability and psychometric robustness of the measurement model. However, it remains important to explore possible sources of misfit or localized non-invariance that could inform refinements to further improve the model.</p>
</section></section><section id="possible-error-sources" class="level1" data-number="4"><h1 data-number="4">
<span class="header-section-number">4</span> Possible Error Sources</h1>
<div id="tbl-lavTestScore-weak" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lavTestScore-weak-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Longitudinal Invariance Sources
</figcaption><div aria-describedby="tbl-lavTestScore-weak-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-bordered table-condensed cell caption-top table-sm small" data-quarto-postprocess="true">
<caption>Assessment of Metric Invariance Based on Score Test (Weak Invariance Model)</caption>
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Restriction Tested</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Chi-square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Evaluation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p2. == .p4.</td>
<td style="text-align: center; width: 3.5cm;">0.440</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.507</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p6. == .p8.</td>
<td style="text-align: center; width: 3.5cm;">0.501</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.479</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p10. == .p12.</td>
<td style="text-align: center; width: 3.5cm;">2.659</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.103</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p14. == .p16.</td>
<td style="text-align: center; width: 3.5cm;">0.661</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.416</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The results of the score test for the weak invariance model, which evaluates the equality of factor loadings across time points, indicate that all tested parameter constraints are supported by the data. Specifically, none of the tested restrictions—such as the equality between parameters <code>.p2.</code> and <code>.p4.</code>, <code>.p6.</code> and <code>.p8.</code>, <code>.p10.</code> and <code>.p12.</code>, and <code>.p14.</code> and <code>.p16.</code>—yielded statistically significant chi-square values. All p-values were well above the conventional threshold of 0.05, suggesting that constraining these loadings to be equal does not lead to a significant deterioration in model fit.</p>
<p>These findings provide strong empirical support for metric (or weak) invariance, meaning that the strength of the relationship between the latent factors and their observed indicators is stable across waves. This level of invariance is a necessary condition for making valid comparisons of structural relationships—such as regression paths or covariances—between latent variables over time. The absence of any violation in the score test results implies that the measurement model functions consistently across the different time points examined.</p>
<div id="tbl-lavTestScore-strong" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lavTestScore-strong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Longitudinal Invariance Sources
</figcaption><div aria-describedby="tbl-lavTestScore-strong-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-bordered table-condensed cell caption-top table-sm small" data-quarto-postprocess="true">
<caption>Assessment of Metric Invariance Based on Score Test (Strong Invariance Model)</caption>
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Restriction Tested</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Chi-square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Evaluation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p2. == .p4.</td>
<td style="text-align: center; width: 3.5cm;">0.095</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.758</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p6. == .p8.</td>
<td style="text-align: center; width: 3.5cm;">0.797</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.372</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p10. == .p12.</td>
<td style="text-align: center; width: 3.5cm;">3.305</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.069</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p14. == .p16.</td>
<td style="text-align: center; width: 3.5cm;">0.421</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.517</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p29. == .p31.</td>
<td style="text-align: center; width: 3.5cm;">0.574</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.449</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p30. == .p32.</td>
<td style="text-align: center; width: 3.5cm;">0.459</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.498</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p33. == .p35.</td>
<td style="text-align: center; width: 3.5cm;">1.675</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.196</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p34. == .p36.</td>
<td style="text-align: center; width: 3.5cm;">2.496</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.114</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p37. == .p39.</td>
<td style="text-align: center; width: 3.5cm;">0.305</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.581</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p38. == .p40.</td>
<td style="text-align: center; width: 3.5cm;">0.060</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.806</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p41. == .p43.</td>
<td style="text-align: center; width: 3.5cm;">1.716</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.190</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p42. == .p44.</td>
<td style="text-align: center; width: 3.5cm;">0.470</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.493</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p45. == .p47.</td>
<td style="text-align: center; width: 3.5cm;">0.071</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.790</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p46. == .p48.</td>
<td style="text-align: center; width: 3.5cm;">0.318</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.573</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p49. == .p51.</td>
<td style="text-align: center; width: 3.5cm;">3.829</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.050</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p50. == .p52.</td>
<td style="text-align: center; width: 3.5cm;">0.914</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.339</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p53. == .p55.</td>
<td style="text-align: center; width: 3.5cm;">0.534</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.465</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p54. == .p56.</td>
<td style="text-align: center; width: 3.5cm;">0.188</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.665</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p57. == .p59.</td>
<td style="text-align: center; width: 3.5cm;">0.008</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.929</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p58. == .p60.</td>
<td style="text-align: center; width: 3.5cm;">0.657</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.418</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>This table presents the results of a series of score tests used to assess potential violations of metric invariance under the strong invariance model. Although each row formally tests the equality of a pair of parameters—typically factor loadings, intercepts, or residual variances—across time points, what is relevant here is the statistical behavior of each restriction, which can signal localized sources of misfit even within an otherwise acceptable global model.</p>
<p>The chi-square statistics associated with each restriction are generally low, and all p-values are well above conventional thresholds for statistical significance. For example, the restriction <code>.p2. == .p4.</code> yields a chi-square of 0.095 and a p-value of 0.758, indicating strong empirical support for the equality of these two parameters. Similarly, other restrictions such as <code>.p38. == .p40.</code> (χ² = 0.060, p = 0.806) and <code>.p57. == .p59.</code> (χ² = 0.008, p = 0.929) suggest that the corresponding parameters are invariant across measurement occasions.</p>
<p>A slightly borderline case appears with <code>.p49. == .p51.</code>, which yields a p-value of 0.050. Although it does not reach conventional significance levels, the relatively higher chi-square statistic (χ² = 3.829) may suggest this parameter deserves closer inspection, especially if similar localized discrepancies accumulate. Nonetheless, based on the p-value threshold used here, none of the tested constraints exhibits a statistically significant violation of invariance.</p>
<p>Taken together, these findings suggest that the tested equality constraints are tenable, and there are no strong indications of local misfit or parameter-level sources of error in this subset of the model. Still, it is essential to interpret these results in the broader context of model fit and theoretical expectations. Isolated non-significant results do not eliminate the need for further examination—particularly in parameters that approach the threshold of concern or that correspond to theoretically critical items. Thus, even when score tests support invariance, researchers should remain attentive to substantive plausibility, potential differential item functioning, or item-specific idiosyncrasies that could influence interpretation.</p>
<div id="tbl-lavTestScore-strict" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lavTestScore-strict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Longitudinal Invariance Sources
</figcaption><div aria-describedby="tbl-lavTestScore-strict-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table table-striped table-bordered table-condensed cell caption-top table-sm small" data-quarto-postprocess="true">
<caption>Assessment of Metric Invariance Based on Score Test (Strict Invariance Model)</caption>
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Restriction Tested</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Chi-square</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">df</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">p-value</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Evaluation</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p2. == .p4.</td>
<td style="text-align: center; width: 3.5cm;">0.108</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.742</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p6. == .p8.</td>
<td style="text-align: center; width: 3.5cm;">0.989</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.320</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p10. == .p12.</td>
<td style="text-align: center; width: 3.5cm;">1.767</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.184</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p14. == .p16.</td>
<td style="text-align: center; width: 3.5cm;">0.060</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.806</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p37. == .p39.</td>
<td style="text-align: center; width: 3.5cm;">0.285</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.593</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p38. == .p40.</td>
<td style="text-align: center; width: 3.5cm;">0.193</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.660</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p41. == .p43.</td>
<td style="text-align: center; width: 3.5cm;">0.874</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.350</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p42. == .p44.</td>
<td style="text-align: center; width: 3.5cm;">0.487</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.485</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p45. == .p47.</td>
<td style="text-align: center; width: 3.5cm;">0.215</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.643</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p46. == .p48.</td>
<td style="text-align: center; width: 3.5cm;">0.456</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.499</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p49. == .p51.</td>
<td style="text-align: center; width: 3.5cm;">3.414</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.065</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p50. == .p52.</td>
<td style="text-align: center; width: 3.5cm;">0.918</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.338</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p53. == .p55.</td>
<td style="text-align: center; width: 3.5cm;">0.007</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.935</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p54. == .p56.</td>
<td style="text-align: center; width: 3.5cm;">0.024</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.878</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p57. == .p59.</td>
<td style="text-align: center; width: 3.5cm;">1.053</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.305</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p58. == .p60.</td>
<td style="text-align: center; width: 3.5cm;">0.360</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.548</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p61. == .p63.</td>
<td style="text-align: center; width: 3.5cm;">0.316</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.574</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p62. == .p64.</td>
<td style="text-align: center; width: 3.5cm;">0.348</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.555</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 5cm;">.p65. == .p67.</td>
<td style="text-align: center; width: 3.5cm;">0.073</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.787</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5cm;">.p66. == .p68.</td>
<td style="text-align: center; width: 3.5cm;">0.006</td>
<td style="text-align: center; width: 3.5cm;">1</td>
<td style="text-align: center; width: 3.5cm;">0.937</td>
<td style="text-align: center; width: 4cm;">No violation</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The table presents the results of score tests used to evaluate metric invariance under the <strong>strict invariance model</strong>, which imposes the strongest set of constraints in longitudinal measurement: equal factor loadings, intercepts, and residual variances across waves. Each row in the table corresponds to a test of the equality between two specific parameters across time points. The chi-square statistic, degrees of freedom (df), and p-value indicate whether that equality constraint significantly worsens model fit, which would suggest a violation of invariance.</p>
<p>In this case, all tested restrictions yield <strong>non-significant</strong> p-values, with none falling below the conventional alpha threshold of 0.05. For example, the constraint <code>.p2. == .p4.</code> produces a chi-square of 0.108 and a p-value of 0.742, strongly suggesting that the two parameters are statistically indistinguishable and thus invariant. Other constraints, such as <code>.p14. == .p16.</code> (χ² = 0.060, p = 0.806) and <code>.p66. == .p68.</code> (χ² = 0.006, p = 0.937), similarly indicate no violation of invariance.</p>
<p>A few parameters show slightly elevated chi-square values and marginal p-values—for instance, <code>.p49. == .p51.</code> yields a chi-square of 3.414 and a p-value of 0.065. While still non-significant, this result is relatively close to the threshold, and the associated parameters might merit further investigation for potential partial invariance or item-level idiosyncrasies.</p>
<p>Overall, the evidence suggests that the model meets the criteria for strict invariance. That is, there is no statistical indication that any of the tested loadings, intercepts, or residuals differ meaningfully across waves. This supports the conclusion that the measurement properties of the constructs remain stable over time. Still, researchers should remain cautious and consider examining parameters close to significance thresholds, exploring possible sources of measurement error, or testing for partial invariance if theoretical or substantive justifications arise.</p>
</section></main><!-- /main column --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>