---
title: "Medición de percepciones y preferencias sobre meritocracia en etapa escolar en Chile"
format:
  html: default
  hikmah-pdf: 
    indent: false
author:
  - name: Juan Carlos Castillo
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: alaffertt@estudiante.uc.cl
    affiliations:
      - ref: 2
  - name: Jesús Díaz
    orcid: 
    email: jesus.diaz.m@ug.uchile.cl
    affiliations:
      - ref: 1
  - name: Benjamín Zavala
    orcid: 
    email: benjamin.zavala.t@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Departmento de Sociología, Universidad de Chile
  - id: 2
    name: Instituto de Sociología, Universidad Católica de Chile 
bibliography: "/Users/macbookair/Documents/GitHub/merit-factorial/input/bib/merit-factorial.bib"
csl: "/Users/macbookair/Documents/GitHub/merit-factorial/input/bib/apa6.csl"
link-citations: true
linestretch: 1.15       
fontsize: 12pt          
geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
papersize: letter
colorlinks: true
fig-height: 4
fig-width: 7.5
---

# Introducción

La creencia en que las disparidades económicas se justifican por diferencias en elementos meritocráticos --- como esfuerzo y talento individual [@young_rise_1958] --- han sido identificadas como mecanismos clave para explicar la persistencia de las desigualdades. Desde sus comienzos, las instituciones educativas han sido fundamentales en la promoción de este tipo de valores, dado su vínculo con las promesas de movilidad social y mejores oportunidades de vida. Ante los desafíos derivados de las diferentes conceptualizaciones y mediciones de la meritocracia, Castillo et al. [-@castillo_multidimensional_2023] proponen un marco conceptual y de medición para evaluar las percepciones y preferencias meritocráticas y no meritocráticas. Con el propósito de contribuir a la investigación empírica sobre la formación de la meritocracia y sus factores relacionados en edades tempranas [@darnon_where_2018; @batruch_belief_2022; @wiederkehr_belief_2015], este estudio se propone evaluar la aplicabilidad de esta escala en población escolar en Chile, un país caracterizado por una aguda y persistente desigualdad económica y que cuenta un sistema educacional altamente estratificado [@corvalan_mercado_2017; @chancel_world_2022].

Argumentamos en primer lugar que existe una distinción entre percepción y preferencias en la meritocracia. Mientras la percepción se asocia a como las personas observan el funcionamiento de principios meritocráticos en la sociedad (lo que es), las preferencias se refieren a juicios normativos (lo que debería ser). La segunda distinción tiene que ver con elementos meritocráticos y no meritocráticos. En este caso, se considera también que aspectos como el rol de los contactos personales y la riqueza familiar no son necesariamente opuestos a la percepción y valoración del esfuerzo y del talento en la obtención de logros y recompensas. 

Para poder establecer en qué medida es posible reconocer las distintas dimensiones de la meritocracia en la población escolar se implementará un procedimiento de análisis factorial confirmatorio en datos de estudiantes chilenos. Además, se realizarán estimaciones de invarianza longitudinal entre dos olas de una muestra de estudiantes en Chile. Finalmente, planteamos que los factores meritocráticos se asocian positivamente con las preferencias por justicia de mercado en salud, pensiones y educación [@lindh_public_2015], mientras lo opuesto ocurre para los factores no meritocráticos.


# Datos, variables y métodos

## Datos
Este estudio se basa en la información proporcionada por la base de datos de la Encuesta Panel Educación y Meritocracia (EDUMER) en sus olas de 2023 (N = 839) y 2024 (N = 612) para estudiantes. Esta base de datos se sustenta en la aplicación de cuestionarios web a estudiantes de sexto básico y primero medio provenientes de 9 escuelas de la región Metropolitana y Valparaíso de Chile. 

## Variables

**Escala de percepciones y preferencias sobre meritocracia**: Las variables incluidas en el modelo de medición sobre percepciones y preferencias de meritocracia y no meritocracia se operacionalizan según los ítems propuestos por Castillo et al. [-@castillo_multidimensional_2023]. La percepción de la meritocracia se mide mediante dos ítems que indagan sobre el grado de acuerdo con que el esfuerzo y la habilidad son recompensados en Chile, mientras que la percepción no meritocrática se mide con dos ítems que evalúan el grado de acuerdo sobre el éxito asociado a contactos y riqueza familiar. La preferencia por la meritocracia se mide con dos ítems que evalúan el acuerdo en que quienes más se esfuerzan o tienen más talento deberían ser más recompensados. La preferencia por aspectos no meritocráticos se mide con dos indicadores que evalúan el acuerdo en que está bien que quienes tienen mejores contactos o padres ricos tengan más éxito. Cada ítem se contestó en una escala Likert de cuatro puntos que va desde "muy en desacuerdo" (1) hasta "muy de acuerdo" (4).

**Preferencias por justicia de mercado**: Este constructo se mide a través de tres variables que abordan el grado de justificación respecto a si el acceso a los servicios sociales en salud, pensiones y educación debe estar condicionado por los ingresos. La justificación de la desigualdad en salud se mide a través del ítem: «¿Está bien que aquellos que puedan pagar más tengan mejor acceso a salud?». La misma pregunta se hace para pensiones y educación. En todos los casos, los encuestados indican sus preferencias en una escala Likert que va desde "muy en desacuerdo" (1) hasta "muy de acuerdo" (4). Además, incluimos un indicador resumido de "preferencias por la justicia de mercado", medido por un índice promedio de todos estos ítems ($\alpha$ = 0,83), con valores que van de 1 a 4, donde los valores más altos representan mayores preferencias por justicia de mercado. 

## Métodos

Para evaluar nuestras hipótesis, empleamos análisis factoriales confirmatorios (CFA) basado en un modelo de medición de cuatro factores latentes [@castillo_multidimensional_2023] con estimador Diagonal Weighted Least Squares (DWLS) debido al nivel ordinal de los ítems [@kline_principles_2023]. La evaluación del ajuste del modelo se fundamentó en los criterios propuestos por Brown [-@brown_confirmatory_2015]: CFI > 0.95; TLI > 0.95; RMSEA < 0.06. 

Para examinar la estabilidad métrica del modelo de medición [@davidov_measurement_2014], realizamos pruebas de invarianza longitudinal utilizando los datos de las dos olas del estudio. En línea con @liu_testing_2017, seguimos un enfoque jerárquico de cuatro modelos: configural (estructura factorial equivalente), débil (igualdad de cargas factoriales), fuerte (igualdad de interceptos) y estricto (igualdad de varianzas de error). Este enfoque resulta especialmente pertinente para indicadores categóricos ordenados, dado que tratar escalas Likert de cuatro puntos como continuas puede introducir sesgos en las estimaciones. Además del criterio basado en el cambio en el valor del chi-cuadrado, adoptamos como indicadores de invarianza el cambio en el CFI ($\Delta \geq -0.010$)  y el RMSEA ($\Delta \geq 0.015$), siguiendo las recomendaciones de Chen (2007).


Finalmente, para evaluar la validez externa del modelo de medición, llevamos a cabo un análisis de regresión entre variables latentes y observadas  [@kline_principles_2023]. Este análisis permitió explorar la relación entre factores meritocráticos y no meritocráticos con las preferencias por la justicia de mercado en salud, pensiones y educación, conforme a la literatura existente [@castillo_socialization_2024].


# Resultados

Los resultados revelan que la escala presenta buenos indicadores de ajuste (CFI = 0.989, TLI = 0.979, RMSEA = 0.046, $\chi^2$ (df = 14) = 39.183) y que sus dimensiones se corresponden con el modelo multidimensional propuesto en población escolar. Se observan altas cargas factoriales (> 0.6) para todos los ítems en sus respectivos factores latentes. Las correlaciones entre factores son consistentes con las observadas en población adulta [@castillo_multidimensional_2023]: la percepción de elementos meritocráticos se asocia negativamente con la percepción de elementos no meritocráticos, mientras que esta última se relaciona positivamente con la preferencia por la meritocracia. Estos hallazgos sugieren que, en una etapa temprana de socialización, los estudiantes diferencian entre cómo perciben el funcionamiento de elementos meritocráticos y no meritocráticos, y cómo prefieren que estos operen en la sociedad. Resulta relevante notar que una mayor percepción de no meritocracia esté vinculada con una mayor preferencia por la misma, destacando la importancia de este principio moral en la formación de valores y actitudes durante la etapa escolar [@batruch_belief_2022; @wiederkehr_belief_2015; @darnon_where_2018].

Los resultados del análisis de invarianza longitudinal no respaldan la estabilidad métrica del modelo. En el nivel de invarianza débil, donde se restringuen las cargas factoriales entre las dos olas, los indicadores sugieren un mal ajuste ($\Delta$ CFI = -0.006, $\Delta$ RMSEA = 0.006). Al examinar el modelo factorial en la segunda ola, se observa que, aunque los ítems se relacionan positivamente con sus respectivos factores, las cargas factoriales muestran cambios en el orden jerárquico. Los ítems relacionados con la percepción o preferencia de los contactos adquieren mayor peso en los factores de no meritocracia, desplazando la preeminencia previa del ítem sobre padres ricos. Este cambio podría explicarse por un proceso de socialización en el cual, con el tiempo, los estudiantes adquieren una mayor comprensión sobre el funcionamiento e importancia de los elementos no meritocráticos en la sociedad.

Los resultados de los modelos de regresión indican que una mayor percepción y preferencia por la meritocracia se asocian positivamente con una mayor preferencia por la justicia de mercado, mientras que esta relación no se observa con los factores no meritocráticos. En detalle, una mayor preferencia por elementos no meritocráticos se asocia con una mayor preferencia por la justicia de mercado. Aunque este hallazgo contradice nuestra hipótesis, resulta coherente bajo la premisa de que preferir que la meritocracia opere a través de contactos o riqueza familiar podría estar vinculado con una mayor aceptación de que el acceso a servicios sociales básicos dependa de la capacidad de pago individual [@castillo_socialization_2024]. 

# Pre-registro

El pre-registro del estudio puede encontrarse en este [link](https://osf.io/2uhrk).

# Referencias

::: {#refs}
:::

```{r}
#| echo: false
#| label: wordstats
#| warning: false
#| message: false
wordcount <- wordcountaddin::text_stats('extended-abstract-demosal2025.qmd')
words <- substr(wordcount[3], start=19, stop=29)
```

**Word count**: `r words`
