---
title: "Meritocracia en la etapa escolar: una validación y aplicación de una escala sobre percepciones y preferencias de meritocracia"
format: pdf
author:
  - name: Juan Carlos Castillo
    corresponding: true
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
      - ref: 2
      - ref: 3
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 4
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 2
  - name: María Fernanda Núñez
    orcid: 0009-0004-7559-9959
    email: maria.nunez.2@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Universidad de Chile
  - id: 2
    name: Centro de estudios del conflicto y cohesión social (COES)
  - id: 3
    name: Núcleo milenio de desigualdades y oportunidades digitales (NUDOS)
  - id: 4
    name: Pontificia Universidad Católica de Chile
lang: es
citeproc: true
---

El aumento de la desigualdad económica y la concentración de la riqueza se ha asociado con una creciente preocupación por estudiar sus implicancias subjetivas. Las creencias de que las sociedades operan y distribuyen las recompensas en función de principios meritocráticos—donde las disparidades económicas se justifican por diferencias en esfuerzo y talento individual— han sido identificadas como uno los mecanismos claves para explicar la persistencia de las desigualdades. Ante los desafíos asociados con las diferentes conceptualizaciones y mediciones de la meritocracia, Castillo et al. (2023) proponen un marco conceptual y de medición para evaluar las percepciones y preferencias meritocráticas y no meritocráticas en contextos de encuestas. Este estudio pretende probar la validez y aplicabilidad de esta propuesta de escala en población escolar en Chile. A partir de los datos de la Encuesta Panel Educación y Meritocracia en sus olas de 2023 (N = 804) y 2024 (N = X) para estudiantes, estimamos análisis factoriales confirmatorios (CFA), pruebas de invariancia y modelos de ecuaciones estructurales. Los resultados preliminares indican que la escala presenta buenos indicadores de ajuste y que sus dimensiones se corresponden con el modelo conceptual multidimensional propuesto, con altas contribuciones factoriales de sus ítems. Con el análisis de invarianza encontramos evidencia que respalda la equivalencia y aplicabilidad de la escala en diferentes muestras medidas en dos puntos de tiempo. Adicionalmente, los modelos de ecuaciones estructurales muestran que la escala predice actitudes políticas en la manera esperada por la evidencia previa, sugiriendo su validez de criterio. Estos hallazgos contribuyen tanto al desarrollo de la medición de la meritocracia y la no meritocracia como a la investigación empírica que examina su relación con diversas actitudes políticas en la etapa escolar en Chile.
