---
title: "Medición de percepciones y preferencias sobre meritocracia en etapa escolar en Chile"
format:
  html: default
  hikmah-pdf: 
    indent: false
author:
  - name: Juan Carlos Castillo
    orcid: 0000-0003-1265-7854
    email: juancastillov@uchile.cl
    affiliations:
      - ref: 1
  - name: Andreas Laffert
    orcid: 0000-0002-9008-2454
    email: alaffertt@estudiante.uc.cl
    affiliations:
      - ref: 2
  - name: Kevin Carrasco
    orcid: 0000-0002-9348-8361
    email: kevin.carrasco@ug.uchile.cl
    affiliations:
      - ref: 3
  - name: María Fernanda Núñez
    orcid: 0009-0004-7559-9959
    email: maria.nunez.2@ug.uchile.cl
    affiliations:
      - ref: 1
affiliations: 
  - id: 1
    name: Departamento de Sociología, Universidad de Chile
  - id: 2
    name: Instituto de Sociología, Universidad Católica de Chile
  - id: 3
    name: Centro de estudios de Conflicto y Cohesión Social
bibliography: "/Users/macbookair/Documents/GitHub/merit-factorial/input/bib/merit-factorial.bib"
csl: "/Users/macbookair/Documents/GitHub/merit-factorial/input/bib/apa6.csl"
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
papersize: letter
colorlinks: true
fig-height: 4
fig-width: 7.5
---

# Introducción

Las creencias de que las sociedades distribuyen sus recompensas en función de principios meritocráticos---donde las disparidades económicas se justifican por diferencias en esfuerzo y talento individual [@young_rise_1958]---han sido identificadas como mecanismos clave para explicar la persistencia de las desigualdades. Desde sus comienzos, las instituciones educativas han sido fundamentales en la promoción de los valores meritocráticos, dado su vínculo con las promesas de movilidad social y mejores oportunidades de vida. Ante los desafíos derivados de las diferentes conceptualizaciones y mediciones de la meritocracia, Castillo et al. [-@castillo_multidimensional_2023] proponen un marco conceptual y de medición para evaluar las percepciones y preferencias meritocráticas y no meritocráticas en contextos de encuestas. Con el propósito de contribuir a la investigación empírica sobre la formación de la meritocracia y sus factores relacionados en edades tempranas [@darnon_where_2018; @batruch_belief_2022; @wiederkehr_belief_2015], este estudio se propone evaluar la aplicabilidad de esta escala en población escolar en Chile, un país caracterizado por una aguda y persistente desigualdad económica y que cuenta un sistema educacional altamente estratificado [@corvalan_mercado_2017; @chancel_world_2022].

Argumentamos en primer lugar que la percepción de la meritocracia es una variable latente construida a partir de indicadores que miden la importancia atribuida al esfuerzo y al talento en la obtención de recompensas. En segundo lugar, sugerimos que la percepción no meritocrática es una variable latente derivada de indicadores que reflejan el acuerdo con afirmaciones sobre el rol de los contactos personales y la riqueza familiar en el éxito en la vida. En tercer lugar, sostenemos que las preferencias meritocráticas funcionan como una variable latente basada en el valor normativo asignado al esfuerzo y talento, mientras que las preferencias no meritocráticas se fundamentan en el valor asignado a los contactos y la riqueza familiar. Respecto a la aplicabilidad y validez de este marco, sostenemos que las escalas de meritocracia y no meritocracia exhiben invarianza métrica entre dos olas de una encuesta panel. Finalmente, planteamos que los factores meritocráticos (no-meritocráticos) se asocian positivamente (negativamente) con las preferencias por justicia de mercado en salud, pensiones y educación [@lindh_public_2015].

# Datos, variables y métodos

## Datos
Este estudio se basa en la información proporcionada por la base de datos de la Encuesta Panel Educación y Meritocracia en sus olas de 2023 (N = 840) y 2024 (N = 840) para estudiantes. Esta base de datos se sustenta en la aplicación de cuestionarios web a estudiantes de sexto básico y primero medio provenientes de 9 escuelas de la región Metropolitana y Valparaíso de Chile. 

## Variables

**Escala de percepciones y preferencias sobre meritocracia**: Las variables incluidas en el modelo de medición sobre percepciones y preferencias de meritocracia y no meritocracia se operacionalizan según los ítems propuestos por Castillo et al. [-@castillo_multidimensional_2023]. La percepción de la meritocracia se mide mediante dos ítems que indagan sobre el grado de acuerdo con que el esfuerzo y la habilidad son recompensados en Chile, mientras que la percepción no meritocrática se mide con dos ítems que evalúan el grado de acuerdo sobre el éxito asociado a contactos y riqueza familiar. La preferencia por la meritocracia se mide con dos ítems que evalúan el acuerdo en que quienes más se esfuerzan o tienen más talento deberían ser más recompensados. La preferencia por aspectos no meritocráticos se mide con dos indicadores que evalúan el acuerdo en que está bien que quienes tienen mejores contactos o padres ricos tengan más éxito. Cada ítem se contestó en una escala Likert de cuatro puntos que va desde "muy en desacuerdo" (1) hasta "muy de acuerdo" (4).

**Preferencias por justicia de mercado**: Este constructo se mide a través de tres variables que abordan el grado de justificación respecto a si el acceso a los servicios sociales en salud, pensiones y educación debe estar condicionado por los ingresos. La justificación de la desigualdad en salud se mide a través del ítem: «¿Está bien que aquellos que puedan pagar más tengan mejor acceso a salud?». La misma pregunta se hace para pensiones y educación. En todos los casos, los encuestados indican sus preferencias en una escala Likert que va desde "muy en desacuerdo" (1) hasta "muy de acuerdo" (4). Además, incluimos un indicador resumido de "preferencias por la justicia de mercado", medido por un índice promedio de todos estos ítems ($\alpha$ = 0,83), con valores que van de 1 a 4, donde los valores más altos representan mayores preferencias por justicia de mercado. 

## Métodos

Para evaluar las hipótesis, empleamos análisis factoriales confirmatorios (CFA) basado en un modelo de medición con cuatro factores latentes con estimador Diagonal Weighted Least Squares (DWLS) debido al nivel ordinal de los ítems [@kline_principles_2023]. Para evaluar la estabilidad métrica del modelo [@davidov_measurement_2014], realizaremos una prueba de invariancia longitudinal con datos de las dos olas del estudio. Siguiendo a @liu_testing_2017, probaremos una serie de cuatro modelos jerárquicos: Configural, Débil, Fuerte y Estricto, específicamente para indicadores categóricos ordenados, dado que una escala Likert de cuatro puntos no puede tratarse como continua sin riesgo de sesgo en las estimaciones. Finalmente, realizaremos un análisis de regresión con variables latentes (modelos de ecuaciones estructurales) para explorar la relación entre factores meritocráticos y no meritocráticos y preferencias por justicia de mercado.

# Resultados

Los resultados preliminares indican que la escala presenta buenos indicadores de ajuste y que sus dimensiones se corresponden con el modelo conceptual multidimensional propuesto, con altas contribuciones factoriales de sus ítems. Con el análisis de invarianza encontramos evidencia que respalda la equivalencia longitudinal de la escala en las dos olas del estudio. Adicionalmente, los modelos de ecuaciones estructurales muestran que la escala predice las preferencias por justicia de mercado en la manera esperada, tanto a nivel agregado como en los ítems por separado. Estos hallazgos contribuyen tanto al desarrollo de la medición de la meritocracia como a la investigación empírica que examina su relación con diversas preferencias por la desigualdad en la etapa escolar en Chile.

# Pre-registro

El pre-registro del estudio puede encontrarse en este [link](https://osf.io/2uhrk).

# Referencias

::: {#refs}
:::

```{r}
#| echo: false
#| label: wordstats
#| warning: false
#| message: false
wordcount <- wordcountaddin::text_stats('extended-abstract.qmd')
words <- substr(wordcount[3], start=19, stop=29)
```

**Word count**: `r words`
