<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Equipo EDUMER">

<title>analisis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="04-analisis_files/libs/clipboard/clipboard.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/quarto.js"></script>
<script src="04-analisis_files/libs/quarto-html/popper.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="04-analisis_files/libs/quarto-html/anchor.min.js"></script>
<link href="04-analisis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="04-analisis_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="04-analisis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="04-analisis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="04-analisis_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="04-analisis_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="04-analisis_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="04-analisis_files/libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="04-analisis_files/libs/bsTable-3.3.7/bootstrapTable.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Equipo EDUMER </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="results" class="level1">
<h1>Results</h1>
<section id="cohort-invariance-test" class="level2">
<h2 class="anchored" data-anchor-id="cohort-invariance-test">Cohort Invariance Test</h2>
<p><img src="imagenes/esquema-basica.jpg" class="img-fluid"></p>
<p>The diagram shows the standardized factor loadings estimated with WLSMV for the primary and secondary education models. One of the first findings is that within each cohort, the loadings vary depending on the factor. In the case of the primary education model, the loadings of both meritocratic perception indicators are quite similar, with perception of effort at .60 and perception of talent at .71. In contrast, in the non-meritocratic preferences factor, the loadings vary greatly, with preference for effort being .46 and preference for talent being .86. This suggests that the factor explains the second factor more than the first. Finally, the indicators of the non-meritocratic preferences factor vary, but not as strongly.</p>
<p><img src="imagenes/esquema-media.jpg" class="img-fluid"></p>
<p>In the secondary education model, some similarities can be seen in comparison to the primary model. The indicators of the meritocratic perception factor have slightly higher loadings than in the previous model, but they do not differ as much from each other. The difference in the indicators of meritocratic preference is reversed, with preference for effort becoming the highest (.76) and preference for talent the lowest (0.41). With regard to non-meritocratic preferences, the indicators have much more similar factor loadings than in the primary school model.</p>
<div class="cell">
<div id="tbl-fitcohort" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fitcohort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Summary fit indices of three models
</figcaption>
<div aria-describedby="tbl-fitcohort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Fit indexes by model</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">chisq</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">pvalue</th>
<th style="text-align: right;">cfi</th>
<th style="text-align: right;">tli</th>
<th style="text-align: right;">rmsea</th>
<th style="text-align: right;">srmr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">General</td>
<td style="text-align: right;">41.026</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.989</td>
<td style="text-align: right;">0.978</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">0.039</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primary</td>
<td style="text-align: right;">36.295</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">0.975</td>
<td style="text-align: right;">0.951</td>
<td style="text-align: right;">0.063</td>
<td style="text-align: right;">0.049</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Secondary</td>
<td style="text-align: right;">10.877</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.696</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.004</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.029</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><a href="#tbl-fitcohort" class="quarto-xref">Table&nbsp;1</a> shows the fit indices for each of the three models. All models achieved a non-significant chi-square, which could be expected given their sensitivity to large samples, such as those used in this study.</p>
<p>The first model is the general model, i.e., the one that includes primary and secondary school students. It can be seen that it has good fit indices (CFI=0.989, RMSEA=0.048, <span class="math inline">\(\chi^2\)</span>(df=14)=41.026), so we can conclude that the four latent factor scale works well for students.</p>
<p>The second model contains data from primary students. In this case, the fit indices work acceptable (CFI=0.975, RMSEA=0.063, <span class="math inline">\(\chi^2\)</span>(df=14)=36. 295). In this case, the scale has less validation than for the previous model.</p>
<p>It is noteworthy that, for the secondary education model, most indicators have values that are close to perfect (CFI=1, RMSEA=0, <span class="math inline">\(\chi^2\)</span>(df=14)=11.779). However, the results of this model could be overfitting, so they should be interpreted with caution.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Cohort invariance</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">chisq</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">rmsea</th>
<th style="text-align: right;">cfi</th>
<th style="text-align: right;">tli</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Configural</td>
<td style="text-align: right;">40.192</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">0.037</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.993</td>
<td style="text-align: right;">0.985</td>
</tr>
<tr class="even">
<td style="text-align: left;">Thresholds</td>
<td style="text-align: right;">77.941</td>
<td style="text-align: right;">34</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">0.979</td>
<td style="text-align: right;">0.965</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Strong</td>
<td style="text-align: right;">91.320</td>
<td style="text-align: right;">38</td>
<td style="text-align: right;">0.000</td>
<td style="text-align: right;">0.058</td>
<td style="text-align: right;">0.974</td>
<td style="text-align: right;">0.962</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The results of the different invariance models are displayed at the previous table. To examine invariance across cohorts the same steps in Dubravka et al.&nbsp;(2019) were followed, who propose the estimation of three models: the configural model, another restricting the thresholds, and finally restricting the thresholds and factor loadings.</p>
<p>The configural model was first estimated, which maintains the same factor structure for both baseline and midline. The configural model has good fit indices (CFI = 0.993, RMSEA = 0.036), so there is empirical evidence that the factor structure behaves stably in both groups.</p>
<p>Looking at the thresholds restricted model, it appears that when thresholds are restricted to equality, the four-factor latent model is not equivalent across the different cohorts in the study in accordance with <span class="citation" data-cites="chen_sensitivity_2007">Chen (<a href="#ref-chen_sensitivity_2007" role="doc-biblioref">2007</a>)</span> (<span class="math inline">\(\Delta\)</span>CFI -.014 &lt; -. 01); <span class="math inline">\(\Delta\)</span>RMSEA .019 &gt; .015). This result implies that by restricting thresholds, the meritocracy scale varies between primary and secondary education. In this case, invariance is not satisfied.</p>
<p>The level represented as strong restricts both thresholds and factor loadings. When compared with the previous level of invariance, it can be seen that the criteria for assuming that the meritocracy scale remains stable across cohorts are not met either. (<span class="math inline">\(\Delta\)</span>CFI -.005 &lt; -. 01); <span class="math inline">\(\Delta\)</span>RMSEA .003 &lt; .015), so invariance is rejected.</p>
<p>It is pertinent to ask to what extent these results are due to the instability of the secondary education model. An attempt was made to resolve its overfitting, but this was not possible, which may have had direct implications for this part of the analysis.</p>
</section>
<section id="longitudinal-invariance" class="level2">
<h2 class="anchored" data-anchor-id="longitudinal-invariance">Longitudinal Invariance</h2>
<p>A series of nested confirmatory factor analysis (CFA) models were estimated to assess the longitudinal measurement invariance of the constructs across the two waves of the study. The evaluation began with the configural model, which allows all parameters (loadings, intercepts, and residuals) to vary freely and just compare the same factor structure within individuals in time. This model served as the baseline for subsequent comparisons and demonstrated good fit to the data, with <span class="math inline">\(\chi^2\)</span>(68) = 117.7, a Comparative Fit Index (CFI) of 0.991, and a Root Mean Square Error of Approximation (RMSEA) of 0.035, with a 90% confidence interval ranging from 0.024 to 0.046. These indices suggest that the same factorial structure is replicated across time points, meaning that the general configuration of items and latent variables remains stable.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-longinv" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longinv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Longitudinal invariance results
</figcaption>
<div aria-describedby="tbl-longinv-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table table-striped table-bordered table-condensed do-not-create-environment cell table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">χ^2 (df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RMSEA (90 CI)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ χ^2 (Δ df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ RMSEA</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Configural</td>
<td style="text-align: center; width: 4cm;">117.7 (68)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.035 (0.024-0.046)</td>
<td style="text-align: center; width: 4cm;">0 (0)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 3.5cm;">Reference</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Weak</td>
<td style="text-align: center; width: 4cm;">122.51 (72)</td>
<td style="text-align: center; width: 4cm;">0.990</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.034 (0.024-0.045)</td>
<td style="text-align: center; width: 4cm;">4.809 (4)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.001</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Strong</td>
<td style="text-align: center; width: 4cm;">128.53 (80)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.032 (0.021-0.042)</td>
<td style="text-align: center; width: 4cm;">6.02 (8)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.002</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Strict</td>
<td style="text-align: center; width: 4cm;">130.17 (84)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.031 (0.02-0.04)</td>
<td style="text-align: center; width: 4cm;">1.635 (4)</td>
<td style="text-align: center; width: 4cm;">0</td>
<td style="text-align: center; width: 4cm;">-0.002</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<p>Subsequently, the weak invariance model was tested by constraining the factor loadings to be equal across waves. This model also showed a fit that passes the acceptable standards indicated by the literature: <span class="math inline">\(\chi^2\)</span>(72) = 122.51, CFI = 0.990, RMSEA = 0.034 (90% CI: 0.024–0.045). The comparison with the configural model revealed a negligible and non-significant change in model fit, with <span class="math inline">\(\Delta \chi^2\)</span>(4) = 4.809, <span class="math inline">\(\Delta\)</span>CFI = 0.000, and <span class="math inline">\(\Delta\)</span>RMSEA = -0.001. These results support the assumption of weak invariance, indicating that the strength of the relationship between items and latent constructs is consistent over time, i.e., within students.</p>
<p>The strong invariance model introduced additional constraints by setting item intercepts and loadings equal across time points, in addition to the equality of thresholds. Fixing thresholds is relevant to ensure that response categories represent equivalent levels of the latent construct across group or time. Whitout threshold invariance, comparisons of latent means may be biased due to differences in how caregories are interpreted rather than true differences in the construct <span class="citation" data-cites="liu_testing_2017">(<a href="#ref-liu_testing_2017" role="doc-biblioref">Liu et al., 2017</a>)</span>. This model yielded a <span class="math inline">\(\chi^2\)</span>(80) = 128.53, CFI = 0.991, and RMSEA = 0.032 (90% CI: 0.021–0.042). The changes in fit statistics relative to the weak model were <span class="math inline">\(\Delta \chi^2\)</span>(8) = 6.02, <span class="math inline">\(\Delta\)</span>CFI = 0.000, and <span class="math inline">\(\Delta\)</span>RMSEA = -0.002. These minimal differences suggest that the additional constraints did not significantly impair the model’s fit. Therefore, strong invariance is supported, meaning that individuals with the same latent trait level are expected to have the same observed item scores across waves.</p>
<p>Finally, the strict invariance model imposed equality constraints on residual variances in addition to the loadings and intercepts. This model also showed good fit: <span class="math inline">\(\chi^2\)</span>(84) = 130.17, CFI = 0.991, RMSEA = 0.031 (90% CI: 0.020–0.040). The comparison with the strong model revealed a <span class="math inline">\(\Delta \chi^2\)</span>(4) = 1.635, <span class="math inline">\(\Delta\)</span>CFI = 0.000, and <span class="math inline">\(\Delta\)</span>RMSEA = -0.002. These changes are minimal and fall well within recommended thresholds for model comparison, indicating that strict invariance is also supported.</p>
<p>In summary, the results support full longitudinal measurement invariance—configural, weak, strong, and strict—suggesting that the constructs are measured equivalently across time. This justifies meaningful comparisons of latent means, variances, and covariances over time, and provides strong evidence of the temporal stability and psychometric robustness of the measurement model. However, it remains important to explore possible sources of misfit or localized non-invariance that could inform refinements to further improve the model.</p>
<p>In parallel, to detect potential sources of local misfit and evaluate the robustness of longitudinal measurement invariance, an univariate score tests was estimated at each level of the invariance hierarchy: configural, metric (weak), scalar (strong), and strict. Using the <code>lavTestScore()</code> function in <em>lavaan</em>, we tested whether specific equality constraints—such as equal loadings, thresholds, or residual variances across time—introduced statistically significant misfit. This method enables the identification of individual parameters that may violate invariance assumptions, even when global model fit remains acceptable.</p>
<p>Across all three constrained models (metric, scalar, and strict), the score tests revealed no significant violations. At the metric level, all loading constraints were supported. In the scalar model, both loadings and thresholds showed stability over time, with no indication of misfit. Finally, under strict invariance, residual variances and thresholds were also found to be invariant across waves. The largest test statistic (<span class="math inline">\(\chi^2\)</span> = 3.829, p = .050) was observed for a threshold in <em>preference for talent indicator</em>, yet this did not reach significance.</p>
<p>These results provide strong evidence that full longitudinal measurement invariance holds in the data. The measurement model is stable over time in terms, supporting meaningful comparison of latent variable means, variances, and structural relations across time. Full results of the score tests, including all tested constraints and their associated statistics, are presented in the supplementary materials.</p>
</section>
<section id="conditional-longitudinal-invariance" class="level2">
<h2 class="anchored" data-anchor-id="conditional-longitudinal-invariance">Conditional Longitudinal Invariance</h2>
<p>Although no evidence was found in favor of measurement invariance between cohorts, the analysis nevertheless explored the potential heterogeneity associated with cohort differences, given the plausible expectation of their impact on socialization processes. To evaluate the robustness of longitudinal measurement invariance over time while accounting for these effects, a series of nested models were estimated, both with and without controlling for cohort through a dummy variable predicting each latent factor.</p>
<p>All models presented fit indices that exceed commonly accepted standards in the literature, with CFI values above .990 and RMSEA values below .035. The configural model (<span class="math inline">\(\chi^2\)</span> = 117.70, df = 68, CFI = .991, RMSEA = .035 [.024–.046]) served as the baseline, and subsequent models imposing equality constraints on factor loadings (weak invariance), intercepts (strong invariance), and residual variances (strict invariance) showed negligible changes in fit indices (e.g., <span class="math inline">\(\Delta\)</span>CFI ≤ .001 across all steps). This pattern held even after including cohort as a covariate: for instance, the strict invariance model with cohort control yielded <span class="math inline">\(\chi^2\)</span> = 134.21 (df = 92), CFI = .991, and RMSEA = .028 [.017–.038], closely resembling the model without cohort control (<span class="math inline">\(\chi^2\)</span> = 130.17, df = 84, CFI = .991, RMSEA = .031 [.020–.040]). These results support the conclusion that full longitudinal measurement invariance is maintained, regardless of cohort-related heterogeneity.</p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-conditional" class="cell quarto-float anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Conditional longitudinal invariance by cohort level
</figcaption>
<div aria-describedby="tbl-conditional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div>
<table class="table table-striped table-bordered table-condensed do-not-create-environment cell table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Model</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">χ^2 (df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">RMSEA (90 CI)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ χ^2 (Δ df)</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ CFI</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Δ RMSEA</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Decision</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Configural</td>
<td style="text-align: center; width: 4cm;">122.27 (76)</td>
<td style="text-align: center; width: 4cm;">0.990</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.032 (0.021-0.042)</td>
<td style="text-align: center; width: 4cm;">0 (0)</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 3.5cm;">Reference</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Weak</td>
<td style="text-align: center; width: 4cm;">126.95 (80)</td>
<td style="text-align: center; width: 4cm;">0.990</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.032 (0.021-0.042)</td>
<td style="text-align: center; width: 4cm;">4.684 (4)</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 4cm;">-0.001</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="odd">
<td style="text-align: center; width: 3.5cm;">Strong</td>
<td style="text-align: center; width: 4cm;">128.55 (88)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.028 (0.017-0.038)</td>
<td style="text-align: center; width: 4cm;">1.598 (8)</td>
<td style="text-align: center; width: 4cm;">0.001</td>
<td style="text-align: center; width: 4cm;">-0.004</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 3.5cm;">Strict</td>
<td style="text-align: center; width: 4cm;">131.64 (92)</td>
<td style="text-align: center; width: 4cm;">0.991</td>
<td style="text-align: center; width: 4cm; width: 5cm;">0.027 (0.016-0.037)</td>
<td style="text-align: center; width: 4cm;">3.086 (4)</td>
<td style="text-align: center; width: 4cm;">0.000</td>
<td style="text-align: center; width: 4cm;">-0.001</td>
<td style="text-align: center; width: 3.5cm;">Accept</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<p>Substantively, these results suggest that the factor structure and measurement properties of the constructs are stable over time and are not significantly influenced by cohort membership. The consistency of the fit indices before and after controlling for cohort indicates that observed longitudinal invariance is not an artifact of generational differences. This strengthens the validity of our interpretations regarding temporal stability and change in the latent constructs under study.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-chen_sensitivity_2007" class="csl-entry" role="listitem">
Chen, F. F. (2007). Sensitivity of <span>Goodness</span> of <span>Fit Indexes</span> to <span>Lack</span> of <span>Measurement Invariance</span>. <em>Structural Equation Modeling: A Multidisciplinary Journal</em>, <em>14</em>(3), 464–504. <a href="https://doi.org/10.1080/10705510701301834">https://doi.org/10.1080/10705510701301834</a>
</div>
<div id="ref-liu_testing_2017" class="csl-entry" role="listitem">
Liu, Y., Millsap, R. E., West, S. G., Tein, J.-Y., Tanaka, R., &amp; Grimm, K. J. (2017). Testing measurement invariance in longitudinal data with ordered-categorical measures. <em>Psychological Methods</em>, <em>22</em>(3), 486–506. <a href="https://doi.org/10.1037/met0000075">https://doi.org/10.1037/met0000075</a>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>