---
title: "Stability and comparability of meritocratic beliefs in school-age students: A measurement invariance approach across time and cohorts"
format:
  pdf: 
    indent: false
    keep-tex: true
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
papersize: letter
colorlinks: true
fig-height: 4
fig-width: 7.5
header-includes:
  - \usepackage{threeparttable}
---

## Acknowledgments

The authors recognize the support of the National Research and Development Agency (ANID) through the grant from the National Fund for Scientific and Technological Development (FONDECYT) N°1250518.

## Exclusive Submission Statement

The authors confirm that this article has been submitted exclusively to this journal. 

## Conflict of Interest

The authors declare no conflict of interest.

## Funding

This research received funding from ANID/FONDECYT grant N°1250518.

## Ethical approval and informed consent statements 

The study received ethical approval from the Research Ethics Committee at the Faculty of Social Sciences, University of Chile. The committee determined that the project posed minimal risk and approved the consent and confidentiality procedures described in the ethical assessment report

## Data Avaibility Statement

The original data presented in the study are openly available in <https://github.com/educacion-meritocracia>

Access to the data, code, and analysis presented in the study are openly available in <https://github.com/educacion-meritocracia/merit-factorial>.

