---
title: "Stability and comparability of meritocratic beliefs in school-age students: A measurement invariance approach across time and cohorts"
format:
  pdf: 
    indent: false
    keep-tex: true
link-citations: true
linestretch: 1.15       
mainfont: Times New Roman
fontsize: 12pt          
geometry: "left=2.54cm,right=2.54cm,top=2.54cm,bottom=2.54cm"
papersize: letter
colorlinks: true
fig-height: 4
fig-width: 7.5
header-includes:
  - \usepackage{threeparttable}
---

## Authors Affiliations and Research Interests

**Andreas Laffert**, Institute of Sociology, Pontifical Catholic University of Chile, Santiago de Chile. Research interests: social stratification, social mobility, wealth, and attitudes towards the marketization of social welfare. 

**Juan Carlos Castillo**, Departament of Sociology, University of Chile, Santiago de Chile. Research interests: distributive justice from a quantitative perspective, using multilevel methods, structural equation modeling, and open science tools. 
    
**René Canales**, Institute of Sociology, Pontifical Catholic University of Chile, Santiago de Chile. Research interests: contentious politics, political attitudes, and social stratification. 

**Tomás Urzúa**, Departament of Sociology, University of Chile, Santiago de Chile. Research interests: sociology of education, meritocracy, and quantitative methods.

**Kevin Carrasco**, Departament of Sociology, University of Chile, Santiago de Chile. Research interests: inequality, distributive justice, civic education, open science, quantitative methods in social research, and survey design.